routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes([
    'register' => false, // Register is false
    'reset' => false,  // Password Reset is false
    'verify' => false, // Email Verification Routes is false
]);



Route::middleware(['auth'])->group(function(){

    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    
    Route::middleware(['admin'])->group(function(){
        
        Route::resource('companies', App\Http\Controllers\CompaniesController::class);
        Route::get('/getdata/companies', [ App\Http\Controllers\CompaniesController::class, 'get_data_json'])->name('companies.getdata');

        Route::resource('employees', App\Http\Controllers\EmployeesController::class);
        Route::get('/getdata/employees', [ App\Http\Controllers\EmployeesController::class, 'get_data_json'])->name('employees.getdata');

    });

});

app/Http/Controllers/CompaniesController.php
<?php

namespace App\Http\Controllers;

// use App\DataTables\CompaniesDataTable;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

use DataTables;
use App\Models\Companies;
use App\Models\Employees;
// use App\DataTables\CompaniesDataTable;

class CompaniesController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth','admin']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('companies.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:255',
            'email' => 'email|max:255|nullable',
            'logo' => 'image|file|mimes:jpeg,jpg,png,gif|max:2048|nullable',
            'url' => 'nullable'
        ]);

        if ($validator->fails()) {
            
            return redirect()->route('companies.create')->withErrors($validator);

        }

        $company = Companies::create($request->all());

        if($request->hasFile('logo')) {
            $file = $request->file('logo');
 
            //you also need to keep file extension as well
            $name = $request->name.'.'.$file->getClientOriginalExtension();
 
            //using the array instead of object
            $image['filePath'] = $name;
            $file->move(storage_path().'/', $name);
            $company->logo= storage_path().'/'. $name;
            $company->save();
         }

        return redirect()->route('companies.index')->with(['message'=>'saved']);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return $id;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, Request $request)
    {
        if($request->ajax()){
            $company_data = Companies::find($id);
            $employees_data = Employees::where('company_id', $id)->pluck('company_id');

            if(empty($employees_data)){
                return response(false);
            }else{
                $company_data->delete();
                return response(true);
            }

        }
    }

    public function get_data_json(Request $request){
        if(!Auth::check()){return redirect()->url('/');}

        if($request->ajax()){

            $data = Companies::get();

            return DataTables::of($data) 
                    ->addColumn('action', function($row){
                        $btn = '<a href= companies/'.$row->id.'/edit class="edit btn btn-warning btn-sm editCompany" type="button">
                                 <span class="fa fa-edit" style="color:white;"></span></a>
                                 <button class="btn btn-danger btn-sm delete" data-id="'.$row->id.'">
                                    <span class="fa fa-trash"></span>
                                 </button>';
                         return $btn;
                    })
                    ->addIndexColumn()  
                    ->setRowId('id')
                    ->rawColumns(['action'])
                    ->make(true);
        }

    }

}

resources/views/companies/create.blade.php
@extends('layouts.app')
@section('pageTitle', 'Create Companies')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header bg-primary"> 
                        <h6 style="color:white;">Create New Company</h6>
                    </div>
                    <div class="card-body">
                        <form id="formCreateCompany" action="{{route('companies.store')}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group has-feedback row">
                                <label for="" class="col-3">
                                    Company Name
                                </label>
                                <div class="col-6">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="fa fa-building" style="width:20px;"></i>
                                            </span>
                                        </div>
                                        <input type="text" class="form-control" name="name" id="name" placeholder="Type Company Name">
                                    </div>
                                    @error('name')
                                    <span class="text-danger">
                                        <strong id="company-name-error">{{$message}}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>                      
                            <div class="form-group has-feedback row">
                                <label for="" class="col-3">
                                    Email
                                </label>
                                <div class="col-6">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="fa fa-envelope" style="width:20px;"></i>
                                            </span>
                                        </div>
                                        <input type="email" class="form-control" name="email" id="email" placeholder="Type Email">
                                    </div>
                                    @error('email')
                                    <span class="text-danger">
                                        <strong id="email-error">{{message}}</strong>
                                    </span>
                                    @enderror
                                </div>                       
                            </div>
                            <div class="form-group has-feedback row">
                                <label for="" class="col-3">
                                    Logo
                                    <br>
                                    <span style="color:red;">*</span> <small><i>max-size:2MB</i></small>
                                </label>
                                <div class="col-6">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" name="logo" id="logo">
                                        <label class="custom-file-label" for="validatedCustomFile">Choose file...</label>
                                    </div>
                                    @error('logo')
                                    <span class="text-danger">
                                        <strong id="logo-error">{{$errors->message}}</strong>
                                    </span>
                                    @enderror
                                </div>                            
                            </div>
                            <div class="form-group has-feedack row">
                                <label for="" class="col-3">
                                    Website
                                </label>
                                <div class="col-6">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="fa fa-link" style="width:20px;"></i>
                                            </span>
                                        </div>
                                        <input type="text" class="form-control" name="url" id="url" placeholder="Type Website URL">
                                    </div>
                                    @error('url')
                                    <span class="text-danger">
                                        <strong id="link-error">{{$message}}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <hr>
                            <div class="row justify-content-end">
                                <div class="col-md-9">
                                    <button type="button" class="btn btn-outline-info" onclick="window.history.back()">
                                        <span><i class="fa fa-long-arrow-left"></i> Back</span>
                                    </button>
                                    <button type="submit" class="btn btn-primary">
                                        <span><i class="fa fa-save"></i> Save</span>
                                    </button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
                   
            </div>
        </div>
    </div>
@endsection

@section('scripts')
<script>
    $(function(){
        $('#logo').on('change', function(){ 
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings("#formCreateCompany .custom-file-label").addClass("selected").html(fileName);   
        });
    });
</script>
@stop

resources/views/companies/index.blade.php
@extends('layouts.app')
@section('pageTitle', 'Companies')
@section('content')

@if (session('success'))
    <script>
        $( document ).ready(function{
            swal.fire("{{ session('success') }}")
        });
    </script>
@endif
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-primary float-right mb-3" id="create-company" href="{{route('companies.create')}}">
                <i class="fa fa-plus"></i> <span>New Company</span>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-bordered" id="companies-table">
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Name</th>
                        <th>Email</th>
                        <!-- <th>Created At</th>
                        <th>Updated At</th> -->
                        <th>Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
    
@endsection

@section('modal')
<!-- <div class="modal" tabindex="-1" role="dialog" id="company-create-modal">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Create New Company</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="formCreateCompany" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group has-feedback row">
                            <label for="" class="col-3">
                                Company Name
                            </label>
                            <div class="col-6">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="fa fa-building" style="width:20px;"></i>
                                        </span>
                                    </div>
                                    <input type="text" class="form-control" name="name" id="name" placeholder="Type Company Name" required>
                                </div>
                                <span class="text-danger">
                                    <strong id="company-name-error"></strong>
                                </span>
                            </div>
                        </div>                      
                        <div class="form-group has-feedback row">
                            <label for="" class="col-3">
                                Email
                            </label>
                            <div class="col-6">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="fa fa-envelope" style="width:20px;"></i>
                                        </span>
                                    </div>
                                    <input type="email" class="form-control" name="email" id="email" placeholder="Type Email">
                                </div>
                                <span class="text-danger">
                                    <strong id="email-error"></strong>
                                </span>
                            </div>                       
                        </div>
                        <div class="form-group has-feedback row">
                            <label for="" class="col-3">
                                Logo
                                <br>
                                <span style="color:red;">*</span> <small><i>max-size:2MB</i></small>
                            </label>
                            <div class="col-6">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input form-control" name="logo" id="logo">
                                    <label class="custom-file-label" for="validatedCustomFile">Choose file...</label>
                                    <div class="invalid-feedback">Example invalid custom file feedback</div>
                                </div>
                                <span class="text-danger">
                                    <strong id="logo-error"></strong>
                                </span>
                            </div>                            
                        </div>
                        <div class="form-group has-feedack row">
                            <label for="" class="col-3">
                                Website
                            </label>
                            <div class="col-6">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="fa fa-link" style="width:20px;"></i>
                                        </span>
                                    </div>
                                    <input type="text" class="form-control" name="url" id="url" placeholder="Type Website URL">
                                </div>
                                <span class="text-danger">
                                    <strong id="link-error"></strong>
                                </span>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Save changes</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div> -->
@endsection

@section('scripts')
<script>
    $(function() {
        var datatable = $('#companies-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{{route("companies.getdata")}}',
            columns: [
                { data: 'DT_RowIndex', name: 'DT_RowIndex'},
                { data: 'name', name: 'name' },
                { data: 'email', name: 'email' },
                // { data: 'created_at', name: 'created_at' },
                // { data: 'updated_at', name: 'updated_at' },
                { data: 'action', name: 'action', orderable: false, searchable: false},
            ]
        });

        $('#companies-table tbody').on('click', '.delete', function (e) {
            xid = $(this).data('id');
            
            swal.fire({
                title: "Are you sure?",
                text: "You will not be able to recover this data!",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete it!"
            }).then ((result) => {
                if(result.isConfirmed){
                    $.ajax({
                        type : "DELETE",
                        url : '{{url("companies/")}}/'+xid,
                        data : { id: xid },
                        success : function(response){
                            if(response == 1){
                                swal.fire("Done!", "It was succesfully deleted!", "success");
                            }else if(response == 0){
                                swal.fire("Nothing to do!", "Data has relation!", "error");
                            }
                            datatable.ajax.reload();
                        },
                        error : function(response){
                            swal.fire("Error deleting!", "Please try again", "error");
                        }
                    });
                }
            });                
        });

       
    });
</script>
@stop