routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes([
    'register' => false, // Register is false
    'reset' => false,  // Password Reset is false
    'verify' => false, // Email Verification Routes is false
]);



Route::middleware(['auth'])->group(function(){

    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    
    Route::middleware(['admin'])->group(function(){
        
        Route::resource('companies', App\Http\Controllers\CompaniesController::class);
        Route::get('/getdata/companies', [ App\Http\Controllers\CompaniesController::class, 'get_data_json'])->name('companies.getdata');

        Route::resource('employees', App\Http\Controllers\EmployeesController::class);
        Route::get('/getdata/employees', [ App\Http\Controllers\EmployeesController::class, 'get_data_json'])->name('employees.getdata');

    });

});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>GRTech - @yield('pageTitle')</title>

    <!-- Scripts -->

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link rel="stylesheet" href="{{asset('asset/css/bootstrap.min.css')}}">
    <link href="{{ asset('asset/css/icons.css') }}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{{asset('asset/css/datatables.min.css')}}">
    <link rel="stylesheet" href="{{asset('asset/css/sweetalert2.min.css')}}">
    <link rel="stylesheet" href="{{asset('asset/css/select2.min.css')}}">
    <link rel="stylesheet" href="{{asset('asset/css/select2-bootstrap.min.css')}}">

    <!-- <link href="{{ asset('css/app.css') }}" rel="stylesheet"> -->
    <style>
        .navbar-nav .nav-link{
            color: #FFFFFF;
        }
    </style>
    
</head>
<body>
    
    @yield('modal')

    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-primary shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}" style="color: white;">
                    GRTech 
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item">
                            <a href="{{route('companies.index')}}" class="nav-link"> Companies</a>
                        </li>
                        <li class="nav-item">
                            <a href="{{route('employees.index')}}" class="nav-link"> Employees</a>
                        </li>

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif
                            
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>

    <!-- <script src="{{ mix('js/app.js') }}"></script> -->
    
    <!-- jQuery -->
    <script src="{{asset('asset/js/jquery-3.5.1.min.js')}}"></script>
    
    
    <!-- DataTables -->
    <script src="{{asset('asset/js/datatables.min.js')}}"></script>
    
    <!-- Bootstrap JavaScript -->
    <script src="{{asset('asset/js/bootstrap.bundle.js')}}"></script>

    <!-- Sweet Alert -->
    <script src="{{asset('asset/js/sweetalert2.min.js')}}"></script>

    <!-- Select2 -->
    <script src="{{asset('asset/js/select2.min.js')}}"></script>

    @yield('scripts')

    <script>
       
        $(function(){
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $(".select-company").select2({
                theme: "bootstrap",
            });

            

          
        });
    </script>
    
    
</body>
</html>